language: node_js
node_js:
    - "stable"
install:
    - npm install -g bower
    - npm run dep
    - export DISPLAY=':99.0'
    - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
    - mkdir -p ./build
script:
    - ./node_modules/.bin/tsc --version
    - ./node_modules/.bin/browserify --version
    - npm run build
    - ./node_modules/.bin/mocha --version
    - nvim --version
    - npm run test
addons:
    apt:
        sources:
            - neovim-ppa/unstable
        packages:
            - xvfb
            - neovim
